version: "3.8"

networks:
  localhost:
    name: inet

services:
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - localhost
    restart: always
    env_file:
      - .env
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_debian
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    expose:
      - "9000"
    restart: always
    env_file:
      - .env
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:var/www/wordpress
    networks:
      - localhost
    restart: always
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: "/home/afraccal/data/wordpress"
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: "/home/afraccal/data/mariadb"
      o: bind
      type: none
