networks:
  localhost:
    name: inet

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/afraccal/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/afraccal/data/mariadb
      o: bind
      type: none

services:
  
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
    networks:
      - backend
    restart: always
    environment:
      - DB_NAME: $(DB_NAME)
      - DB_USER: $(DB_USER)
      - DB_PASSWORD: $(DB_PASSWORD)
      - MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}

  
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_debian
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
    environment:
      - DB_HOST: ${DB_HOST}
      - DB_NAME: ${DB_NAME}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
